### ISSUE TITLE
Multi-culture support for formatting numbers and datetime.

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/wok#104]
As per Multi-culture support standards, user should be able to see the number/datetime as per the browser's settings(locale based on browser's settings). For example, even if user has selected English in UI login panel but browser setting has language as French, then user should able to see UI in English(translation) but Format of number and date time should be French.

"Locale is based on browser's setting" i.e the server gets the value of http "accept-language" header.

Please feel free to provide inputs on these aspects.

**Comment by laggarcia** [comment]
Not sure if I agree with this. If I select the UI to be in English, I'd say everything should be localized to English (including number/date and time), regardless of the Browser configuration. But maybe it is just that I really don't know anything about multi-culture support standards. :)

**Comment by danielhb** [comment]
Getting the "Accept-Language" header is not trivial and not widely supported using standard JS library. Need to check if Bootstrap supports it. I'd say to count with navigator.languages (http://w3c.github.io/html/webappapis.html#dom-navigator-languages) but this is a new specification that is not available in the stable browsers releases, for now.

The bigger issue here is that we need to either follow the browser or WoK setting for everything. I do not believe that allowing WoK to be in one language and the number format in another is a good design.

Now, you mentioned "As per Multi-culture support standards". Is there an open document containing these standards?

**Comment by danielhb** [comment]
The only scenario I could come up with where it would be acceptable to have English language and browser number/datetime is when we do not support the language the user wants. We can create a new WoK language option called 'Other (English, numbers in browser locale)'  for these cases. Using this setting would default WoK to English and the datetime to whatever language the user browser is set.

In the end we'll be mixing languages anyway but at least we're telling the user what we're doing. What we can't do is set the language to English and use comma as decimal mark because my browser is Portuguese.

**Comment by laggarcia** [comment]
I still think we should just follow what the user selects in wok and that's it, for both numbers/date and time and language.

**Comment by danielhb** [comment]
Well, the whole discussion is based on this:

```As per Multi-culture support standards, user should be able to see the number/datetime as per the browser's settings(locale based on browser's settings).```

@archu-s where did you get this info?

**Comment by archu-s** [comment]
I see translation and culture as two different aspects in globalization front.
However, as you mention if we go with list of lang listed in drop-down list we are restricting the multi-culture to the number of languages listed in drop-down list.

So in that case, as you mention "Other" in the list can be one option, which looks good to me. But again we are restricting lang to be English for translation if user want to use any other lang for culture.

So if we need to look for a way where translation lang does not get restricted due to culture lang and vice verse.

**Comment by pkulkark** [comment]
For Datetime, instead of changing the format based on cultural preference, it would be better to display it in ISO format.

**Comment by chandrureddy** [comment]
@danielhb @archu-s @pkulkark @laggarcia 

To be clear in our understanding:
A Locale represents regional settings, that control how numbers, dates, and times display for your region – which may be a country, or a portion of country or may not even honor country boundaries. They are independent of your language. Setting a thread’s locale or changing your system locale will change how numbers, dates, and times are displayed for controls created on that thread or running on your system, respectively.

A language, on the other hand, is what we speak, read, and write. Language settings control in what language text appears independently of the locale settings.

I found some articles which talks about the locale but I see that it is not a good idea to use the HTTP Accept-Language header alone to determine the locale of the user.

https://www.w3.org/International/questions/qa-accept-lang-locales
https://www.w3.org/International/questions/qa-lang-priorities.en

I agree that "Locale based on browser's setting" may not be great idea. With that said, I am just wondering based on the language selected in the tool, will it be good idea to derive locale and represent the information ?

Just a thought !!!

Regards
Chandra

**Comment by chandrureddy** [comment]
@alinefm @danielhb @archu-s @pkulkark 

I would propose the following now ....

We support only 11 languages as part of languages supported by the tool.
Now when it comes to multi cultural support, I feel we should not limit to just 11 languages and instead support as many locale's as we can, which are not tightly coupled to your languages selections.

Therefore I would recommend the following:
1. Allow a way to support multicultural support by just not restricting to the language selection option from the tool ie. not just limit to 11 language we support at the moment.
2. Instead better have a way where locale of the machine or browser etc... By this means user have a choice let us say choose language as English (since his/her preferred language not supported at the moment)  but at-least have the opportunity to have the locale as of his/her choice. Explained in detail in the example above.

since we do have not have better alternative, I would propose to use browser settings to choose the locale of the user.

Please let me know !!!

Regards
Chandra

**Comment by laggarcia** [comment]
If we were to have multi-cultural / localization support, I don't think we can rely on information from the browser. We would probably need an additional drop-down menu in the Wok login interface for the user to select that.

**Comment by chandrureddy** [comment]
@laggarcia  +1: 

I am fine with that approach too. However we have to think about the possible locale selections. 
As per my understanding Coding may not be big issue but little bit of testing effort to confirm the locale settings shown correct.

Regards
Chandra

**Comment by pkulkark** [comment]
@laggarcia :+1: 

@archu-s @alinefm @danielhb @chandrureddy 
I will begin the implementation of this approach. In case someone has a better approach please share.

**Comment by alinefm** [comment]
@laggarcia @chandrureddy @danielhb @archu-s @pkulkark 

I agree we need to have a separated drop down menu for locale. And it can work the same way the language drop menu works.

When user accesses Wok for the first time, Wok gets the browser language and checks if it is part of those 11 languages we have translations for. If so, Wok uses that language to load the UI. If not, it falls back to English.

The browser language can be overridden by the language drop down menu, which creates a browser cookie to store the user selection. So after choosing one language from the drop down menu, that will be used for the next accesses to Wok. But if user clears the browser cookies, it will get back the browser language. 

We could do the same for locale IMO.

**Comment by archu-s** [comment]
Thanks everyone for input. We can close this issue as its now part of upstream code.
