### ISSUE TITLE
Session Handling and Page Redirection

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/wok#15]
![login_1 1](https://cloud.githubusercontent.com/assets/511072/12194864/2cd1619e-b619-11e5-9a61-4419efa79d07.png)
![login1 2](https://cloud.githubusercontent.com/assets/511072/12194865/2cd552fe-b619-11e5-97b6-b5334ad6c104.png)

1. Post session expire when we try to navigate through tabs we get server error pages.

2. Post session expire if we have any pop up window open and try some operation login page appears in pop up window and post authentication pop up gets closed and on browser we get server errors
3. Home page it gives error message : The server encountered an unexpected condition which prevented it from fulfilling the request.

**Comment by alinefm** [comment]
Hi @rajatgupta21!

Could you provide step by step on how to reproduce it?

**Comment by alinefm** [comment]
I was not able to reproduce it with the current upstream code (8131d34e33bd47dd21e69776017a9e694d85ee3b)

Since Wok notifications were added, there is a polling to /notifications API which will notice the session was expired before any user interaction and redirect the user to login page. Probably, that solves this issue.

Please, reopen if the problem persists and provide details on how to reproduce.
